### ISSUE TITLE
define IC

### ISSUE THREAD

**Issue by shannonpileggi** [akgold/akg_site#9]
Hi Alex! I'm really enjoying your unfinished thoughts on management! One small thing is that you refer to the acronym `IC` but I don't think you have defined `IC`. Looking forward to the rest of your thoughts!

**Comment by alexkgold** [comment]
Thank you Shannon! And yes, I definitely need to do this.

**Comment by alexkgold** [comment]
Thanks again for feedback, @shannonpileggi -- sorry it took me so long to get to it :)
